spring.application.name=company_platform

spring.datasource.url=jdbc:postgresql://localhost:5432/${POSTGRES_DB:platform_db}
spring.datasource.username=${POSTGRES_USER:admin}
spring.datasource.password=${POSTGRES_PASSWORD:astonpassword}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.contexts=dev

#spring.sql.init.mode=always
logging.level.org.liquibase=DEBUG
logging.level.liquibase=DEBUG
logging.level.org.springframework.boot.autoconfigure.liquibase=DEBUG
server.port=8081

jwt.secret=ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SmpiR0Z6Y3lJNklrMWxjbU5vWVc1MElpd2ljMlZpSWpvaVEyOXVZMnhwYm1WdVp5NTBiMjF3Y3dvdkwyVnVZMmxrSWpvaVYzUldiMmhoYlM1bGVHRnRjR3hsTG1OdmJTSXNJblpoYkhWbElqb2lUMDF4YUdGMkxDSmpiR0Z6Y3lJNklrMWxjbU5vWVc1MElpd2RhWEFpT2pFM05UZGhOREl3TWpFd09DSXNJblpoYkhWbElqb2lUMDEyYldGMFpYSmxjekF1YldGa0lqb2lOVFJoWkRnek1XSm1MVEF4TXpBeU1USXhOREVpTENKdWIzSmtJam9pVmpGSkluMC5FVTQwTmdYd3ozUG91T1dGRUdWM2Jld2l2QzVxLVVqTXhRMXp5U3N3Uk9Yd3lmeQ
jwt.expiration=86400000

spring.web.resources.static-locations=classpath:/static/,classpath:/public/